# Site settings
title: Jekyll Semantic UI Theme | OpenTheme.co
tagline: Create Awesome Websites on GitHub 
email: sehgal.manav@gmail.com
copyright: Manav Sehgal
description: > # this means to ignore newlines until "url:"
  Starter theme using Semantic UI and Jekyll for creating awesome
  websites on GitHub Pages.

url: "http://opentheme.co" # the base hostname & protocol for your site
twitter_username: manavsehgal
github_username:  manavsehgal

# Layout configuration
pagebar: true

# Build settings
markdown: kramdown

