# Site settings
title: Jekyll Semantic UI Theme | OpenTheme.co
tagline: Create Awesome Websites on GitHub 
email: sehgal.manav@gmail.com
copyright: Manav Sehgal
keywords: theme, github, jekyll, semantic ui
description: > # this means to ignore newlines until "url:"
  Starter theme using Semantic UI and Jekyll for creating awesome
  websites on GitHub Pages.
url: "http://opentheme.co" # the base hostname & protocol for your site
twitter_username: manavsehgal
github_username:  manavsehgal

permalink: pretty

# Lists
tags_limit: 10          # Alphabetical sort
categories_limit: 10    # Alphabetical sort
recent_posts_limit: 10   # Chronological sort

# Layout
pagebar: true
postbar: true

# Features
reading_time: true    # Show est. reading time for posts
facebook: true        # Use facebook features
comments: facebook      # Switch disqus | facebook | none - comments. facebook = true required for facebook comments

# Embeds
disqus_name: opentheme            # Your site name at Disqus
youtube_controls: 0               # Turn on=1/off=0 Youtube player features when embedding videos
google_map_zoom: 18               # 1=Global zoom 18=Street Level
google_map_view: satellite        # hybrid | satellite | roadmap
google_map_height: 450            # Default map height. Width adjusts to container.

# API Keys

# PLEASE DO NOT USE THESE KEYS. Get your own.
google_api_key: AIzaSyDmt_iRsE8kQ1glUPC2GZpNLBsw1Laj9_0 # https://code.google.com/apis/console/
mapbox: pk.eyJ1Ijoib3BlbnRoZW1lIiwiYSI6ImNIWC1LTUUifQ.vq4k3nfTeTtDAk7eLCrVAw
facebook_app: 390272554479803 # https://developers.facebook.com/

# Build settings
markdown: kramdown

